# This file was generated by GoReleaser. DO NOT EDIT.
class Diceroller < Formula
  desc "Deliver Go binaries as fast and easily as possible"
  homepage "https://derp.com"
  url "https://github.com/lukemilby/diceroller/releases/download/v0.1.2/diceroller_0.1.2_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
  version "0.1.2"
  sha256 "fcfc3d36801689c351ccdc2174809c258644469c4b518a88c7f36251ee2babdf"

  def install
    bin.install "diceroller"
  end
end
